### ISSUE TITLE
Confidant fails in a sketchy way when there aren't any `config.js` files in the tree

### ISSUE THREAD

**Issue by lambdabaa** [gaye/confidant#6]
```
gareth@albee:~/Documents/gaia$ ./node_modules/.bin/confidant 
/home/gareth/Documents/gaia/node_modules/confidant/build/ninja_stream.js:29
  tasks.forEach(function (task) {
        ^
TypeError: undefined is not a function
    at NinjaStream._transform (/home/gareth/Documents/gaia/node_modules/confidant/build/ninja_stream.js:29:9)
    at NinjaStream.Transform._read (_stream_transform.js:179:10)
    at NinjaStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at NinjaStream.Writable.write (_stream_writable.js:217:11)
    at Filter.ondata (_stream_readable.js:540:20)
    at Filter.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Filter.Readable.push (_stream_readable.js:126:10)
```

**Comment by lambdabaa** [comment]
This was actually an instance of a different issue. This one works for me.
